### ISSUE TITLE
小米10打开闪退

### ISSUE THREAD

**Issue by Minori-ty** [niuhuan/nhentai-cross#1]

**Comment by niuhuan** [comment]
安卓版本是多少？什么架构？

**Comment by niuhuan** [comment]
arm或者arm64选择自己手机的架构

**Comment by Minori-ty** [comment]
> arm或者arm64选择自己手机的架构

可以了，不过能写个接口文档吗？我也想玩一下

**Comment by niuhuan** [comment]
> > arm或者arm64选择自己手机的架构
> 
> 可以了，不过能写个接口文档吗？我也想玩一下

列表用htmlPaser，漫画用 /g/{galleryId}接口

**Comment by Minori-ty** [comment]
> htmlPaser

比如搜索api，登录api，漫画详情页api，收藏api

**Comment by niuhuan** [comment]
> > htmlPaser
> 
> 比如搜索api，登录api，漫画详情页api，收藏api

这个我没有做，可以参考NClient2
