### ISSUE TITLE
favourite与账户登录问题

### ISSUE THREAD

**Issue by QLozin** [niuhuan/nhentai-cross#12]
很好用的app，希望能详细讲解如何使用内置的“从网址登录”功能，尝试了几次都没有成功，或者成功了但是没找到favourite按钮和收藏夹。感谢

**Comment by niuhuan** [comment]
并没有开发收藏夹 ，web页面是为了绕过防ddos。

🐑🐑🐑🐑🐑

**Comment by niuhuan** [comment]
这个需求是可以实现的，不过最近没有时间。

**Comment by QLozin** [comment]
> 这个需求是可以实现的，不过最近没有时间。

感谢回复，您可以在合适的时候实现他。
