### ISSUE TITLE
感觉可以搭个node的api服务器，或者是打成npm包

### ISSUE THREAD

**Issue by Minori-ty** [niuhuan/nhentai-cross#3]
就是把你写的这些api都集成到node服务中，然后再写个接口文档就行了，这样别人下载你的文件，只需要执行node index,js，就能获取api，也不用管算法和盐值要怎么实现。别人只需要API.get()，或者API.search()，就能实现接口获取。
或者是打成npm包，我记得ehentai是有npm包的，https://www.npmjs.com/package/nhentai。
还有，你的nhentai-app的首页是通过类似爬虫的方法，爬取他的html页面再解析的吗？

**Comment by niuhuan** [comment]
对的, 列表直接爬HTML, 没有盐值, n站只有web端, 接口都能直接用. 可以直接写一个解析器一起用, 不过服务器太耗费成本了, 这个软件的主要特点是不需要科学上网.

**Comment by Minori-ty** [comment]
> 对的, 列表直接爬HTML, 没有盐值, n站只有web端, 接口都能直接用. 可以直接写一个解析器一起用, 不过服务器太耗费成本了, 这个软件的主要特点是不需要科学上网.

我说的服务是本地服务，类似本地的web服务。

**Comment by niuhuan** [comment]
> > 对的, 列表直接爬HTML, 没有盐值, n站只有web端, 接口都能直接用. 可以直接写一个解析器一起用, 不过服务器太耗费成本了, 这个软件的主要特点是不需要科学上网.
> 
> 我说的服务是本地服务，类似本地的web服务。

这样做的目的是给pc用吗？

**Comment by Minori-ty** [comment]
> 这样做的目的是给pc用吗？

对，搭建web网站用的。或者是如果个人喜欢的话，也可以放到服务器，当作个人网站。

**Comment by niuhuan** [comment]
因为只有两个接口所以不需要单独封装
一个是列表, 另外一个是获取图片

**Comment by Minori-ty** [comment]
> 因为只有两个接口所以不需要单独封装 一个是列表, 另外一个是获取图片

不只是这个项目，还有哔咔的，禁漫天堂的

**Comment by niuhuan** [comment]
几个接口都比较简单，你如果想做的话，可以参考项目里面go语言部分，nodejs性能并不是很好，也不利于维护。

**Comment by Minori-ty** [comment]
> 几个接口都比较简单，你如果想做的话，可以参考项目里面go语言部分，nodejs性能并不是很好，也不利于维护。

看得头疼，你看能不能抽离出来，go也行，放个api文档，我做web站调用一下

**Comment by niuhuan** [comment]
现有项目都没有时间去维护呢。你想实现什么应该尽量自己动手，而不是让别人去做。
