### ISSUE TITLE
Release中ipa上传错误

### ISSUE THREAD

**Issue by ghost** [niuhuan/nhentai-cross#4]
v0.0.4_nosign.ipa只有166bytes
![09366EA6-A339-42C0-ABBE-1B6B3FE76CF2](https://user-images.githubusercontent.com/89573386/149954754-6c51f015-c765-49bb-b46a-e781298f70d1.jpeg)

**Comment by niuhuan** [comment]
az

**Comment by niuhuan** [comment]
改好了
