### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by Minori-ty** [niuhuan/nhentai-cross#9]
dns拦截器是怎么实现的？内置代理吗？内置代理请求又是怎么实现的？
比如我现在有一台境外的服务器，我请求的时候，要怎么设置？以及服务器要怎么配置？

**Comment by niuhuan** [comment]
dns override 

不使用Dns解析得到的IP，而是使用固定的Ip，去建立TCP链接，手动cdn。

**Comment by Minori-ty** [comment]
> dns override 
> 
> 不使用Dns解析得到的IP，而是使用固定的Ip，去建立TCP链接，手动cdn。

什么意思？就是不用域名去请求，而是用ip去请求数据？

**Comment by niuhuan** [comment]
> > dns override
> > 不使用Dns解析得到的IP，而是使用固定的Ip，去建立TCP链接，手动cdn。
> 
> 什么意思？就是不用域名去请求，而是用ip去请求数据？

TCP层用IP，Http层保持不变用域名。

**Comment by niuhuan** [comment]
这个功能跟代理没有关系，甚至还有冲突。

**Comment by Minori-ty** [comment]
> > > dns override
> > > 不使用Dns解析得到的IP，而是使用固定的Ip，去建立TCP链接，手动cdn。
> > 
> > 什么意思？就是不用域名去请求，而是用ip去请求数据？
> 
> TCP层用IP，Http层保持不变用域名。

好的
